name: Deploy to Github

on:
  pull_request:
    types: [closed]
    branches:
      - master

env:
  NODE_VERSION: '14.2.0'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          npm install
          tsc --sourceMap false --removeComments
      - name: Zip Release
        # You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@a1afcab9c664c9976ac398fa831eac67bed1eb0e
        uses: TheDoctor0/zip-release@0.4.1
        with:
          # Filename for archive
          filename: release.zip # default is release.zip
          # Base path for archive files
          path: . # optional, default is .
          # Working directory before zipping
          directory: . # optional, default is .
          # List of excluded files / directories
          # exclusions: # optional, default is 
          # Tool to use for archiving
          type: zip # optional, default is zip
